docs(book-cc): document the process for adding new workspace crates
future-proof-iot/RIOT-rs pull request #273
Opened 2024-04-24 09:12 UTC by ROMemories

Not sure the Coding Conventions is the best place to document this, maybe we should have a book section for documenting processes.

2024-04-24 09:15 UTC, kaspar030 requested changes

2024-04-24 09:15 UTC, kaspar030 commented on book/src/coding-conventions.md
> +1. Move the `[lints]` section in its `Cargo.toml` above the `[dependencies]` section.
This and the next need to be more specific I think, I wouldn't know which to move/copy

2024-04-24 10:24 UTC, elenaf9 commented on book/src/coding-conventions.md
> +1. If the new crate is feature-gated and if this possible, add the feature that enables it to the ones used by cargo doc in `.github/workflows/main.yml` and in `.github/workflows/build-deploy-docs.ym
```suggestion
1. Create the new crate's directory in `src/`.
2. Run `cargo init --lib` in that directory.
3. In the new crate's `Cargo.toml`, move the automatically added  `[lints]` section above the `[dependencies]` section.
4. Add a `#![deny(clippy::pedantic)]` lint to the new crate's root module, along with other relevant lints (e.g., `#![deny(missing_docs)]`); some lints are already inherited from the workspace and do not need to be added to the new crate.
5. Cargo has added the crate to the workspace members in the workspace's `Cargo.toml`, move the added string to its own line.
6. Add the crate to the list of crates checked by clippy in `.github/workflows/main.yml`.
7. Consider adding the crate to the list of crates run by cargo test in `.github/workflows/main.yml`.
8. Re-export the crate from the `riot-rs` crate, inline it in the docs as done for the other crates, and feature-gate it if necessary.
9. If the new crate is feature-gated and if this possible, add the feature that enables it to the ones used by cargo doc in `.github/workflows/main.yml` and in `.github/workflows/build-deploy-docs.yml`.
```

2024-04-24 10:33 UTC, elenaf9 commented on book/src/coding-conventions.md
> +1. Add a `#![deny(clippy::pedantic)]` lint to the new crate's root module, along with other relevant lints (e.g., `#![deny(missing_docs)]`); some lints are already inherited from the workspace and do
Why require the `#![deny(clippy::pedantic)]`? We only have it in `riot-rs-benchmarks` and `riot-rs-macros` right now. 
Generally, I don't really think this whole line is necessary; it's nothing RIOT-rs specific.

2024-04-24 10:34 UTC, elenaf9 commented on book/src/coding-conventions.md
> +1. If the new crate is feature-gated and if this possible, add the feature that enables it to the ones used by cargo doc in `.github/workflows/main.yml` and in `.github/workflows/build-deploy-docs.ym
```suggestion
1. If the new crate is feature-gated and if this is possible, add the feature that enables it to the ones used by cargo doc in `.github/workflows/main.yml` and in `.github/workflows/build-deploy-docs.yml`.
```

2024-04-25 10:25 UTC, elenaf9 commented on book/src/coding-conventions.md
> +1. Add a `#![deny(clippy::pedantic)]` lint to the new crate's root module, along with other relevant lints (e.g., `#![deny(missing_docs)]`); some lints are already inherited from the workspace and do
> not having the `pedantic` lint is not the project's policy

Is there a related discussion somewhere, where I can read up upon the reasoning?

2024-11-15 11:33 UTC, kaspar030 requested changes

2024-11-15 11:33 UTC, kaspar030 commented on book/src/coding-conventions.md
> +1. Add relevant lints (e.g., `#![deny(missing_docs)]` and `#![deny(clippy::pedantic)]`) to the crate; some lints are already inherited from the workspace and do not need to be added to the new crate.
I think this needs to be more specific. Better state e.g., "Add `#![deny(missing_docs)]` and `#![deny(clippy::pedantic)]` to the crate"

2024-11-15 11:33 UTC, kaspar030 commented on book/src/coding-conventions.md
> +1. Cargo has added the crate to the workspace members in the workspace's `Cargo.toml`, move the added string to its own line, preserving lexicographic order.
```suggestion
1. In the workspace's `Cargo.toml` `workspace.members`, ensure the crate's entry keeps the lexicographic order.
```

2024-11-15 11:33 UTC, kaspar030 commented on book/src/coding-conventions.md
> +1. Re-export the crate from the `riot-rs` crate, inline it in the docs as done for the other crates, and feature-gate it if necessary.
move to third place (after "add lints", before the CI fixes start)

2024-11-15 11:33 UTC, kaspar030 commented on book/src/coding-conventions.md
> +1. Add the crate to the list of crates checked by Clippy in `.github/workflows/main.yml`, preserving lexicographic order.
This and the next I found not obvious and thus skipped it. Can we have ANCHORS in those yamls? :)

2025-01-07 08:15 UTC, kaspar030 commented on book/src/coding-conventions.md
> +1. If the crate has tests that can be run with `cargo test`:
hm, good question. I was more thinking of the future where the crates will have embedded-test based tests, and I think crates might have to choose.
So this was meant like "if it is this: ... [else, ...]" with the else branch missing. :)

2025-02-08 08:58 UTC, kaspar030 commented on book/src/coding-conventions.md
> +1. In the workspace's `Cargo.toml` `workspace.members` array, ensure the new entry preserves the lexicographic order of that array.
```suggestion
1. In the workspace's `Cargo.toml` `workspace.members` array, ensure the new entry preserves the lexicographic order of that array.
1. In the workspace's `Cargo.toml` `dependencies` array, add a (properly sorted) entry.
```

... I think we'll get rid of the path dependencies soon ...

2025-02-08 10:58 UTC, kaspar030 commented on book/src/coding-conventions.md
> +1. If the crate has tests that can be run with `cargo test`:
So I was thinking about this.

"If the crate has tests that can be run with `cargo test`" => probably no new crate has any tests in the beginning. Maybe we should just add "next steps" and there point to documentation how to add them?

2025-02-08 10:58 UTC, kaspar030 commented
I followed those steps for `ariel-os-alloc`, they work as-is.

2025-03-04 09:19 UTC, kaspar030 approved these changes

2025-03-04 10:29 UTC, merged